image: maven:latest

stages:
  - build
#  - test
  - push

variables:
  MAVEN_CLI_OPTS: "-s ./ci_settings.xml --batch-mode"
  MAVEN_OPTS: ""
  DOCKER_NAME: "services"
  DOCKER_PORT: "9099"
  REGISTRY_PROD: "mddutn/colmena"

cache:
  paths:
    - .m2/repository/
    - target/


BUILDING:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true
  only:
    refs:
      - develop
      
#TESTING: 
#  stage: test 
#  script: 
#    - mvn $MAVEN_CLI_OPTS test
#  only:
#    refs:
#      - develop
#      - master


PUSHING-GIT-LAB:

  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - echo  $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
  
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":"$CI_PIPELINE_IID"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":"latest"
    
    - docker push "$CI_REGISTRY_IMAGE":"$CI_PIPELINE_IID"
    - docker push "$CI_REGISTRY_IMAGE":"latest"
  only:
    refs:
      - develop
      
       
PUSHING-DOCKER-HUB:
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - echo $DOCKERHUB_PWD | docker login -u $DOCKERHUB_USR --password-stdin 
  script:
    - docker build -t "$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"$CI_PIPELINE_IID" .
    
    - docker tag "$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"$CI_PIPELINE_IID" "$REGISTRY_PROD":"$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"$CI_PIPELINE_IID"
    - docker tag "$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"$CI_PIPELINE_IID" "$REGISTRY_PROD":"$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"latest"
    
    - docker push "$REGISTRY_PROD":"$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"$CI_PIPELINE_IID"
    - docker push "$REGISTRY_PROD":"$CI_COMMIT_REF_NAME"-"$CI_PROJECT_NAME"-"latest"
    
  only:
    refs:
      - master